# Generated by Django 5.1.7 on 2025-05-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_cart_cartitem_cart_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Unpaid", "Unpaid"),
                    ("Payment Pending", "Payment Pending"),
                ],
                default="Unpaid",
                max_length=15,
            ),
        ),
    ]
