# Generated by Django 5.1.7 on 2025-05-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_order_payment_id_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
